<script lang="ts">
	import { HugeiconsIcon } from '@hugeicons/svelte';
	import {
		CubeIcon,
		GridViewIcon,
		Layers01Icon,
		AiChat02Icon,
		ChartLineData01Icon,
		BookOpen01Icon,
		ArrowRight01Icon,
		ArrowLeft01Icon,
		ArrowUpRight01Icon,
		PlayIcon,
		PauseIcon,
		VolumeHighIcon,
		Settings01Icon,
		Search01Icon,
		Cancel01Icon,
		Rotate01Icon,
		FullScreenIcon,
		Target01Icon,
		LinkSquare01Icon,
		InformationCircleIcon,
		Fuel01Icon,
		EngineIcon,
		CheckmarkCircle02Icon,
		SentIcon,
		Key01Icon,
		RefreshIcon,
		EyeIcon,
		KeyboardIcon,
		MoveThreeDIcon,
		SquareSplitHorizontalIcon,
		CylinderIcon,
		Structure01Icon,
		PerspectiveIcon,
		SquareIcon,
		OrthogonalEdgeIcon,
		LayoutTopIcon,
		FlipHorizontalIcon,
		EyeOffIcon,
		FocusIcon,
		StopIcon,
		Layout2RowIcon,
		LayoutTable01Icon,
		LayoutLeftIcon,
		LayoutRightIcon,
		Sun01Icon,
		Undo02Icon,
		Redo01Icon,
		RulerDimensionLineIcon,
		GithubIcon,
		Orbit01Icon,
		FastWindIcon,
		FireIcon,
		WindIcon
	} from '@hugeicons/core-free-icons';
	const icons = {
		cube: CubeIcon,
		grid: GridViewIcon,
		layers: Layers01Icon,
		ai: AiChat02Icon,
		chart: ChartLineData01Icon,
		book: BookOpen01Icon,
		right: ArrowRight01Icon,
		left: ArrowLeft01Icon,
		arrow: ArrowUpRight01Icon,
		play: PlayIcon,
		pause: PauseIcon,
		volume: VolumeHighIcon,
		settings: Settings01Icon,
		search: Search01Icon,
		close: Cancel01Icon,
		rotate: Rotate01Icon,
		expand: FullScreenIcon,
		target: Target01Icon,
		link: LinkSquare01Icon,
		info: InformationCircleIcon,
		fuel: Fuel01Icon,
		engine: EngineIcon,
		check: CheckmarkCircle02Icon,
		send: SentIcon,
		key: Key01Icon,
		reset: RefreshIcon,
		eye: EyeIcon,
		keyboard: KeyboardIcon,
		explode: MoveThreeDIcon,
		section: SquareSplitHorizontalIcon,
		cylinder: CylinderIcon,
		tree: Structure01Icon,
		perspective: PerspectiveIcon,
		front: SquareIcon,
		side: OrthogonalEdgeIcon,
		top: LayoutTopIcon,
		flip: FlipHorizontalIcon,
		'eye-off': EyeOffIcon,
		isolate: FocusIcon,
		stop: StopIcon,
		split: Layout2RowIcon,
		table: LayoutTable01Icon,
		properties: LayoutLeftIcon,
		inspector: LayoutRightIcon,
		lighting: Sun01Icon,
		undo: Undo02Icon,
		redo: Redo01Icon,
		ruler: RulerDimensionLineIcon,
		github: GithubIcon,
		orbit: Orbit01Icon,
		air: WindIcon,
		combustion: FireIcon,
		exhaust: FastWindIcon
	};
	let {
		name,
		size = 20,
		strokeWidth = 1.8
	}: { name: keyof typeof icons; size?: number; strokeWidth?: number } = $props();
</script>

{#key name}
	<HugeiconsIcon icon={icons[name]} {size} {strokeWidth} aria-hidden="true" />
{/key}
